name: Helm Chart Build & Push

on:
  workflow_call:
    inputs: 
       buildContext:
        description: 'path for build'
        type: string
        default: "deployment/helm"
        required: false

jobs:
  setup:
    uses: SchulzeStZSI/xfsc-dev-ops/.github/workflows/build-context.yml@main
    secrets: inherit

  helm-push:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use IMAGE_TAG
        run: | 
          echo "The image tag is: ${{ needs.setup.outputs.image_tag }}"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Find and Push Helm Charts
        env: 
          HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
          HARBOR_PROJECT: ${{ needs.setup.outputs.harbor_project }}
          HARBOR_PASSWORD: ${{ needs.setup.outputs.harbor_password }}
          HARBOR_USERNAME: ${{ needs.setup.outputs.harbor_username }}
        run: |
          helm registry login "$HARBOR_HOST" \
            --username "$HARBOR_USERNAME" \
            --password "$HARBOR_PASSWORD"
  
          CHART_DIR="${{ inputs.buildContext }}"
          cd "$CHART_DIR"
      
          # Helm Dependency Build
          helm dependency build
      
          # Helm Package
          helm package .

          CHART_NAME=$(grep '^name:' Chart.yaml | awk '{print $2}')
    
          PACKAGE_FILE="${CHART_NAME}-*.tgz"

          helm push $PACKAGE_FILE oci://$HARBOR_HOST/$HARBOR_PROJECT
